# Group Post
## post [/post]
### リスト表示　[GET]
+ Response 200 (application/json)
    + Attributes
        + data (array[Blog], fixed-type)
### リスト表示　[GET /post2]
+ Response 200 (application/json)
    + Attributes (array[Blog], fixed-type)

# Data Structures
## Blog (object)
+ title: Hello world (string) - ブログタイトル
+ `publish_date`: `2020-01-01 09:00:00` (string) 