FORMAT: 1A
HOST: https://example.com/api/v1

# API Documents

# OVERVIEW
このドキュメントはAPIBlueprintのデモです

::: note 
インフォメーション的な感じで使う
:::

::: warning
警告的なものに使う
:::

<!-- include(message.apib) -->
<!-- include(blog.apib) -->